/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_chinatsp_tautotest_serialport_SerialPort
#define _Included_chinatsp_tautotest_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Java_com_example_androidserialport_serialport_SerialPort_open
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_example_androidserialport_serialport_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     Java_com_example_androidserialport_serialport_SerialPort_close
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidserialport_serialport_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
